### ISSUE TITLE
Failed to parse: //data:image/png;base64 error when I use HttpUserWithResources

### ISSUE THREAD

**Issue by luisromanbcn** [SvenskaSpel/locust-plugins#102]
Hi,

I want to test a site using HttpUserWithResources that contains base64 encoded images but I get the next error every time I try to test it:

[2022-11-23 10:31:41,410] 793c5fb16fd4/ERROR/locust.user.task: Failed to parse: //data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAFCAYAAAB8ZH1oAAAAAklEQVR4AewaftIAAACOSURBVGNmAIIzRw4z9Or9l2zfceELAw7AzAAEk/hvRrPdvVSW4ux4YMKJG1/mzZnD7Ofnx7Zp06a/DFDAzAAEVbYWH1nuPQu+/YPtq3RIgsa7d+8Nvn3/Jmlna2tiZ2vHdujQoecsDEDwnVngGRObxEQ9bt49+zg4OF3tbD7cfvhIipGRkevnr19fGUgBAAWYNT6R2HMiAAAAAElFTkSuQmCC
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/locust/user/task.py", line 347, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.10/dist-packages/locust/user/task.py", line 372, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.10/dist-packages/locust/user/task.py", line 493, in execute_task
    task(self.user)
  File "/code/locust.py", line 10, in my_first_task
    self.client.get("")
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/locust_plugins/users/resource.py", line 117, in wrapper
    self.client.request("GET", resource, name=resource_name, include_resources=False)
  File "/usr/local/lib/python3.10/dist-packages/locust_plugins/users/resource.py", line 103, in wrapper
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/locust/clients.py", line 135, in request
    response = self._send_request_safe_mode(method, url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/locust/clients.py", line 203, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 631, in urlopen
    parsed_url = parse_url(url)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/url.py", line 397, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: //data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAFCAYAAAB8ZH1oAAAAAklEQVR4AewaftIAAACOSURBVGNmAIIzRw4z9Or9l2zfceELAw7AzAAEk/hvRrPdvVSW4ux4YMKJG1/mzZnD7Ofnx7Zp06a/DFDAzAAEVbYWH1nuPQu+/YPtq3RIgsa7d+8Nvn3/Jmlna2tiZ2vHdujQoecsDEDwnVngGRObxEQ9bt49+zg4OF3tbD7cfvhIipGRkevnr19fGUgBAAWYNT6R2HMiAAAAAElFTkSuQmCC

**Comment by luisromanbcn** [comment]
is from an internal URL, but in the production site I checked that it is not happening.

Do you have any way to avoid this URL when it appears?

**Comment by cyberw** [comment]
try setting `default_resource_filter` on your User class or call. see https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/embedded_resource_manager_ex.py

**Comment by abhishek813** [comment]
is there any documentation for this filter and also, what does the include_resources option do?

**Comment by cyberw** [comment]
Just that example and the code itself, should be easy enough to read

**Comment by abhishek813** [comment]
So my understanding is that any resource provided as a regular expression in default_resource_filter would be ignored. Based on that and the original example I tried 
`class QuickstartUser(HttpUserWithResources):
    default_resource_filter=".*[^(data:image)]$"`

and 

`class QuickstartUser(HttpUserWithResources):
    default_resource_filter=".*[^(data:image/png)]$"`

neither of these worked and I continue to get the following error. Can you tell us how to use this option so that Locust ignores base64 encoded images.
`[2022-11-24 14:29:42,769] de86fb732615/ERROR/locust.user.task: Failed to parse: //data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAFCAYAAAB8ZH1oAAAAAklEQVR4AewaftIAAACOSURBVGNmAIIzRw4z9Or9l2zfceELAw7AzAAEk/hvRrPdvVSW4ux4YMKJG1/mzZnD7Ofnx7Zp06a/DFDAzAAEVbYWH1nuPQu+/YPtq3RIgsa7d+8Nvn3/Jmlna2tiZ2vHdujQoecsDEDwnVngGRObxEQ9bt49+zg4OF3tbD7cfvhIipGRkevnr19fGUgBAAWYNT6R2HMiAAAAAElFTkSuQmCC
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/locust/user/task.py", line 347, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.10/dist-packages/locust/user/task.py", line 372, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.10/dist-packages/locust/user/task.py", line 493, in execute_task
    task(self.user)
  File "/code/usps/locust.py", line 26, in homepage
    self.client.get("")
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/locust_plugins/users/resource.py", line 117, in wrapper
    self.client.request("GET", resource, name=resource_name, include_resources=False)
  File "/usr/local/lib/python3.10/dist-packages/locust_plugins/users/resource.py", line 103, in wrapper
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/locust/clients.py", line 135, in request
    response = self._send_request_safe_mode(method, url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/locust/clients.py", line 203, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 631, in urlopen
    parsed_url = parse_url(url)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/url.py", line 397, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: //data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAFCAYAAAB8ZH1oAAAAAklEQVR4AewaftIAAACOSURBVGNmAIIzRw4z9Or9l2zfceELAw7AzAAEk/hvRrPdvVSW4ux4YMKJG1/mzZnD7Ofnx7Zp06a/DFDAzAAEVbYWH1nuPQu+/YPtq3RIgsa7d+8Nvn3/Jmlna2tiZ2vHdujQoecsDEDwnVngGRObxEQ9bt49+zg4OF3tbD7cfvhIipGRkevnr19fGUgBAAWYNT6R2HMiAAAAAElFTkSuQmCC`

**Comment by cyberw** [comment]
Try running it in the debugger

**Comment by cyberw** [comment]
I didnt actually write this User so I dont know that much :)
