### ISSUE TITLE
AttributeError: module 'select' has no attribute 'epoll' (playwright)

### ISSUE THREAD

**Issue by ksulovska** [SvenskaSpel/locust-plugins#104]
Hi, 
I ran into issues with this and would really appreciate if someone knows what to do with it, as I'm complete rookie here. 

So I'm running the test in dev-container (Ubuntu-22.04), python 3.10., but it wasn't better in non-containerized environment. I tried both variants with either using the script or "manual" code. Neither work anywhere, unfortunately. I got very lovely error when running my locustfile. I got the same error when the example file is run.

`Traceback (most recent call last):
  File "/home/vscode/.local/bin/locust", line 8, in <module>
    sys.exit(main())
  File "/home/vscode/.local/lib/python3.10/site-packages/locust/main.py", line 68, in main
    docstring, _user_classes, shape_class = load_locustfile(_locustfile)
  File "/home/vscode/.local/lib/python3.10/site-packages/locust/util/load_locustfile.py", line 58, in load_locustfile
    imported = source.load_module()
  File "<frozen importlib._bootstrap_external>", line 548, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1063, in load_module
  File "<frozen importlib._bootstrap_external>", line 888, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/test/automation/load_testing/locustfile3.py", line 4, in <module>
    from locust_plugins.users.playwright import PlaywrightScriptUser, pw, event, run_single_user, PageWithRetry
  File "/home/vscode/.local/lib/python3.10/site-packages/locust_plugins/users/playwright.py", line 2, in <module>
    from playwright.async_api import async_playwright, Playwright, Browser, Page, BrowserContext
  File "/home/vscode/.local/lib/python3.10/site-packages/playwright/async_api/__init__.py", line 25, in <module>
    import playwright.async_api._generated
  File "/home/vscode/.local/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "/home/vscode/.local/lib/python3.10/site-packages/playwright/_impl/_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "/home/vscode/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 24, in <module>
    from pyee import EventEmitter
  File "/home/vscode/.local/lib/python3.10/site-packages/pyee/__init__.py", line 120, in <module>
    from pyee.trio import TrioEventEmitter as _TrioEventEmitter  # noqa
  File "/home/vscode/.local/lib/python3.10/site-packages/pyee/trio.py", line 7, in <module>
    import trio
  File "/home/vscode/.local/lib/python3.10/site-packages/trio/__init__.py", line 18, in <module>
    from ._core import (
  File "/home/vscode/.local/lib/python3.10/site-packages/trio/_core/__init__.py", line 27, in <module>
    from ._run import (
  File "/home/vscode/.local/lib/python3.10/site-packages/trio/_core/_run.py", line 2452, in <module>
    from ._io_epoll import EpollIOManager as TheIOManager
  File "/home/vscode/.local/lib/python3.10/site-packages/trio/_core/_io_epoll.py", line 188, in <module>
    class EpollIOManager:
  File "/home/vscode/.local/lib/python3.10/site-packages/trio/_core/_io_epoll.py", line 189, in EpollIOManager
    _epoll = attr.ib(factory=select.epoll)
AttributeError: module 'select' has no attribute 'epoll'. Did you mean: 'poll'?`

Is there, please, any easy fix. I really have issues testing that page with simple requests. Thanks in forward.

**Comment by cyberw** [comment]
Sorry, I dont know what is causing this. It has worked for me on OSX and Ubuntu.

**Comment by bonnis** [comment]
I had a similar issue, I was running locust in Manjaro and it showed a very similar error. I found the solution in this issue here #74. Setting the env var LOCUST_PLAYWRIGHT=1 while running locust seems to solve the problem for me. 

This command works for me:
```
LOCUST_PLAYWRIGHT=1 locust
```

**Comment by luisromanbcn** [comment]
I just got the same error and I had to use the LOCUST_PLAYWRIGHT=1 env variable too

**Comment by ionutab** [comment]
I had the same issue and this helped. Not sure why though. it works now, but I have no idea why 😸

**Comment by vokash3** [comment]
> I had a similar issue, I was running locust in Manjaro and it showed a very similar error. I found the solution in this issue here #74. Setting the env var LOCUST_PLAYWRIGHT=1 while running locust seems to solve the problem for me.
> 
> This command works for me:
> 
> ```
> LOCUST_PLAYWRIGHT=1 locust
> ```

Thanks a lot! It works!

Added LOCUST_PLAYWRIGHT=1 to value.yaml for kuber

**Comment by ionutab** [comment]
I hope this will help.
Yesterday, I looked through my package list in the project to see which packages had new releases in the last weeks.
When I explicitly set 
`httpcore==0.17.2`
in my `requirements.txt` file and things are working fine.
When I bump to
`httpcode==0.17.3` the error occurs again and I need to set `LOCUST_PLAYWRIGHT=1` in order for things to work.

**Comment by ksulovska** [comment]
Yes, makes sense, thanks! I'm currently using the LOCUST_PLAYWRIGHT=1 and it's working.

**Comment by cyberw** [comment]
I try to catch this error and give a good instruction here: https://github.com/SvenskaSpel/locust-plugins/blob/69e449e4d4185f922bdc9a963e8b01e7a49ad63f/locust_plugins/users/playwright.py#L4C1-L4C1, but maybe we need to also catch AttributeError

**Comment by cyberw** [comment]
I wasnt quite able to reproduce this, but I tried to fix it (or rather fix the error message). Can someone try out the new release (3.4.0) without setting LOCUST_PLAYWRIGHT and see that you get the improved error message?

**Comment by ksulovska** [comment]
![632](https://github.com/SvenskaSpel/locust-plugins/assets/105634000/b45fc826-4017-4f57-9ad3-cda824f3265d)

This is what I get with upgraded 3.4.0 version without LOCUST_PLAYWRIGHT

**Comment by cyberw** [comment]
Aha! I think the problem is that you are importing playwright-things *before* PlaywrightUser. Then ”our” code has no way of catching the exception. Hmm…

**Comment by cyberw** [comment]
Really? Can you show an example? Callstack & code & platform

**Comment by ksulovska** [comment]
I can, sure.
So it's running in Ubuntu 22.04 LTS in WSL2, Python 3.10.6. It's really possible I'm doing it wrong, but it was working like 1.5 months back during our release phase.

`import random
import string
import requests
from locust import HttpUser, TaskSet, task, between


class MessagesServerTasks(TaskSet):
    def __init__(self, parent):
        super().__init__(parent)
        self.csrftoken = ""
        self.sessionid = ""
        self.case_id = ""  # just one id

    def on_start(self):
        # minimally getting the token must be on_start function, otherwise it doesn't work properly
        with self.client.get("/login", catch_response=True, name="Got token") as response:
            if "login" in response.text and response.elapsed.total_seconds() < 5.0:
                response.success()
                cookies = requests.utils.dict_from_cookiejar(response.cookies)
                self.csrftoken = cookies.get("csrftoken", "")
            else:
                response.failure("Page took too long to load and/or text check has failed.")

        with self.client.post(
            "/api/login_user?next_url=/",
            {"username": "xxx", "password": "xxx"},
            headers={"X-CSRFToken": self.csrftoken},
            name="Logged in",
        ) as post_response:
            cookies = requests.utils.dict_from_cookiejar(post_response.cookies)
            self.sessionid = cookies.get("sessionid", "")
            self.csrftoken = cookies.get("csrftoken", "")

        response = self.client.get(
            "/api/cases", headers={"X-CSRFToken": self.csrftoken}, name="Case list reached, data obtained"
        ).json()
        scan_ids = []
        if "results" in response:
            for result in response["results"]:  # getting IDs from 20 rows per page!
                for scan in result["scans"]:
                    url_parts = scan["url"].split("/")
                    scan_id = url_parts[-1]
                    scan_ids.append(scan_id)

        if scan_ids:
            self.case_id = random.choice(scan_ids)  # random ID from the list of first 20 cases
        else:
            print("No cases present in the Case list. Go and upload something!")

    @task(1)
    def go_to_case(self):
        self.client.get(
            f"/api/case/{self.case_id}#messaging",
            name="Messaging tab obtained",
        )

    def on_stop(self):
        self.client.get("/logout", name="Logged out")


class MessagesServer(HttpUser):
    tasks = [MessagesServerTasks]  # task(s) to be run
    wait_time = between(3, 12)  # hooomans!
`

and the Traceback is: 
![640](https://github.com/SvenskaSpel/locust-plugins/assets/105634000/87ba7e77-140f-49ff-a269-00c5bac32414)

**Comment by cyberw** [comment]
I dont see how that callstack can match that locusfile?

**Comment by ksulovska** [comment]
Well, that's the thing...I can't get anything more out of it. What's even weirder, it sometimes works just straight away. It's seriously driving me nuts time to time.

**Comment by cyberw** [comment]
That is very strange… I dont suppose you have a file named locust.py, playwright.py or something else that might collide? Or maybe a custom python load path env var? Or a locust.conf file that does something special?

**Comment by cyberw** [comment]
Weird… if doctor_cloud_iteration.py doesnt have that import statement on line 8 like the callstack says then it is almost magic..

**Comment by ksulovska** [comment]
Line 8 is actually just an empty space. That's on line 14. And the other issue is, it's in traceback, but the file I ran is called server_message.py

**Comment by cyberw** [comment]
Delete or rename both files?

**Comment by ionutab** [comment]
> I hope this will help. Yesterday, I looked through my package list in the project to see which packages had new releases in the last weeks. When I explicitly set `httpcore==0.17.2` in my `requirements.txt` file everything works fine. When I bump to `httpcode==0.17.3` the error occurs again and I need to set `LOCUST_PLAYWRIGHT=1` in order for things to work.

I've done no changes to my requirements file since commenting this and this morning this issue popped up again 😞 
I've added back the `LOCUST_PLAYWRIGHT=1` to the env vars and everything seems to be working fine.

requirements.txt

```
dataclasses-json==0.5.12
python-dotenv==1.0.0
paho-mqtt==1.6.1
locust-plugins==3.3.1
httpcore==0.17.2
requests~=2.31.0
locust~=2.15.1
gevent==23.7.0
Flask~=2.3.2
urlexpander~=0.0.37

**Comment by cyberw** [comment]
> > I hope this will help. Yesterday, I looked through my package list in the project to see which packages had new releases in the last weeks. When I explicitly set `httpcore==0.17.2` in my `requirements.txt` file everything works fine. When I bump to `httpcode==0.17.3` the error occurs again and I need to set `LOCUST_PLAYWRIGHT=1` in order for things to work.
> 
> I've done no changes to my requirements file since commenting this and this morning this issue popped up again 😞 I've added back the `LOCUST_PLAYWRIGHT=1` to the env vars and everything seems to be working fine.
> 
> requirements.txt
> 
> ```
> dataclasses-json==0.5.12
> python-dotenv==1.0.0
> paho-mqtt==1.6.1
> locust-plugins==3.3.1
> httpcore==0.17.2
> requests~=2.31.0
> locust~=2.15.1
> gevent==23.7.0
> Flask~=2.3.2
> urlexpander~=0.0.37
> ```

But you are importing/using PlaywrightUser, right? Not like ksulovska that gets this error regardless?

**Comment by ionutab** [comment]
Unfortunately, I'm getting this error regardless.
I'm not using anything playwright related in my codebase.

**Comment by cyberw** [comment]
What does your callstack look like? Is it also nonsensical like ksulovskas? Are you also on windows/wsl?

**Comment by ionutab** [comment]
👇 here it is
```Traceback (most recent call last):
  File "/opt/venv/bin/locust", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.10/site-packages/locust/main.py", line 75, in main
    docstring, _user_classes, shape_class = load_locustfile(_locustfile)
  File "/opt/venv/lib/python3.10/site-packages/locust/util/load_locustfile.py", line 58, in load_locustfile
    imported = source.load_module()
  File "<frozen importlib._bootstrap_external>", line 548, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1063, in load_module
  File "<frozen importlib._bootstrap_external>", line 888, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "tests/mqtt/locustfile_mqtt_connections_authorized.py", line 8, in <module>
    from libs.users.MyAuthorizedMqttUser import MyAuthorizedMqttUser
  File "/home/locust/libs/users/MyAuthorizedMqttUser.py", line 14, in <module>
    from libs.users.MyMqttUser import MyMqttUser
  File "/home/locust/libs/users/MyMqttUser.py", line 5, in <module>
    from locust_plugins.users import MqttClient
  File "/opt/venv/lib/python3.10/site-packages/locust_plugins/users/__init__.py", line 6, in <module>
    from .mqtt import *
  File "/opt/venv/lib/python3.10/site-packages/locust_plugins/users/mqtt.py", line 10, in <module>
    import paho.mqtt.client as mqtt
  File "/opt/venv/lib/python3.10/site-packages/paho/mqtt/client.py", line 72, in <module>
    import dns.resolver
  File "/opt/venv/lib/python3.10/site-packages/dns/resolver.py", line 30, in <module>
    import dns._ddr
  File "/opt/venv/lib/python3.10/site-packages/dns/_ddr.py", line 12, in <module>
    import dns.nameserver
  File "/opt/venv/lib/python3.10/site-packages/dns/nameserver.py", line 5, in <module>
    import dns.asyncquery
  File "/opt/venv/lib/python3.10/site-packages/dns/asyncquery.py", line 38, in <module>
    from dns.query import (
  File "/opt/venv/lib/python3.10/site-packages/dns/query.py", line 63, in <module>
    import httpcore
  File "/opt/venv/lib/python3.10/site-packages/httpcore/__init__.py", line 1, in <module>
    from ._api import request, stream
  File "/opt/venv/lib/python3.10/site-packages/httpcore/_api.py", line 5, in <module>
    from ._sync.connection_pool import ConnectionPool
  File "/opt/venv/lib/python3.10/site-packages/httpcore/_sync/__init__.py", line 1, in <module>
    from .connection import HTTPConnection
  File "/opt/venv/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 10, in <module>
    from .._synchronization import Lock
  File "/opt/venv/lib/python3.10/site-packages/httpcore/_synchronization.py", line 13, in <module>
    import trio
  File "/opt/venv/lib/python3.10/site-packages/trio/__init__.py", line 19, in <module>
    from ._core import TASK_STATUS_IGNORED as TASK_STATUS_IGNORED  # isort: skip
  File "/opt/venv/lib/python3.10/site-packages/trio/_core/__init__.py", line 21, in <module>
    from ._local import RunVar
  File "/opt/venv/lib/python3.10/site-packages/trio/_core/_local.py", line 5, in <module>
    from . import _run
  File "/opt/venv/lib/python3.10/site-packages/trio/_core/_run.py", line 2543, in <module>
    from ._io_epoll import EpollIOManager as TheIOManager
  File "/opt/venv/lib/python3.10/site-packages/trio/_core/_io_epoll.py", line 189, in <module>
    class EpollIOManager:
  File "/opt/venv/lib/python3.10/site-packages/trio/_core/_io_epoll.py", line 190, in EpollIOManager
    _epoll = attr.ib(factory=select.epoll)
AttributeError: module 'select' has no attribute 'epoll'. Did you mean: 'poll'?

**Comment by cyberw** [comment]
Looks like httpcore imports trio, just like Playwright does and needs the same workaround (early import of trio). I *could* make it so that locust automatically imports trio if it is available (instead of relying on LOCUST_PLAYWRIGHT env var). I’m a bit hesitant to do that because it will implicitly change behaviour based on a package being installed, which is a little weird. But I guess that could work..

**Comment by ionutab** [comment]
@cyberw if more context will help.
I have a docker image based on Locus which I'm using. I rarely run locally, although I could try.
The image is something like this:

```
FROM locustio/locust:2.15.1

USER root

RUN apt update && \
    apt install -y git netcat procps &&  \
    apt list --upgradable &&  \
    apt -y dist-upgrade && \
    pip install --upgrade --no-cache-dir pip && \
    apt clean all && \
    rm -rf /var/cache/apt

USER locust

# SOME DEFAULT ENV VARS
ENV LOCUST_PLAYWRIGHT=1

#RUN
COPY --chown=locust:locust ./requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt
#RUN pip install -r requirements.txt

COPY --chown=locust:locust /libs libs
COPY --chown=locust:locust ./tests tests
# SOME EXTERNAL ENV VARS
COPY --chown=locust:locust .env .env

EXPOSE 8089 5557
```

I'm running from windows, not in WSL

**Comment by cyberw** [comment]
So it was an issue with httpcore? Thats the only diff I see?

**Comment by cyberw** [comment]
Yea that seems to be it: https://github.com/encode/httpcore/pull/692

**Comment by ness-alexandru-bujdei** [comment]
Yes,
It seems to be an issue with `httpcore`. I've run though multiple iterations today and I need to mention that downgrading to `httpcore==0.17.1` seemed to fix it.

**Comment by cyberw** [comment]
I am working on a solution that removes the need for LOCUST_PLAYWRIGHT env var completely. But for now you can just `uninstall trio` and remove the env var.
