### ISSUE TITLE
[ApplicationInsights] AttributeError: 'WorkerRunner' object has no attribute 'spawn_rate'

### ISSUE THREAD

**Issue by specialforest** [SvenskaSpel/locust-plugins#139]
I'm getting the following exception when using ApplicationInsights plugin with locust 2.15.1:

```
Uncaught exception in event handler: 
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/locust/event.py", line 40, in fire
    handler(**kwargs)
  File "/opt/venv/lib/python3.10/site-packages/locust_plugins/appinsights_listener.py", line 31, in request
    custom_dimensions = self._create_custom_dimensions_dict(
  File "/opt/venv/lib/python3.10/site-packages/locust_plugins/appinsights_listener.py", line 38, in _create_custom_dimensions_dict
    custom_dimensions = self._safe_return_runner_values()
  File "/opt/venv/lib/python3.10/site-packages/locust_plugins/appinsights_listener.py", line 61, in _safe_return_runner_values
    runner_values["spawn_rate"] = str(self.env.runner.spawn_rate)
AttributeError: 'WorkerRunner' object has no attribute 'spawn_rate'
```

**Comment by specialforest** [comment]
Looking at the source code it looks like only [`MasterRunner`](https://github.com/locustio/locust/blob/d68758e339d47eba6a430629db0b23a01d37ca5b/locust/runners.py#L661) has `spawn_rate` attribute.

**Comment by cyberw** [comment]
Strange. @Guilhermeslucas wrote this.
