### ISSUE TITLE
NotImplementedError: unsupported platform

### ISSUE THREAD

**Issue by fannigurt** [SvenskaSpel/locust-plugins#142]
Testing WebSocket example from the docs on fresh installation:
https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/socketio_ex.py

locust                   2.16.1
locust-plugins           3.4.2

Got this error

```
(test-service-py3.11) ➜  load_tests git:(main) ✗ locust                   
Traceback (most recent call last):
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/bin/locust", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/lib/python3.11/site-packages/locust/main.py", line 81, in main
    docstring, _user_classes, shape_class = load_locustfile(_locustfile)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/lib/python3.11/site-packages/locust/util/load_locustfile.py", line 58, in load_locustfile
    imported = source.load_module()
               ^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 605, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1120, in load_module
  File "<frozen importlib._bootstrap_external>", line 945, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/username/codding/test_service/wallet_app/external/load_tests/locustfile.py", line 4, in <module>
    from locust_plugins.users.socketio import SocketIOUser
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/lib/python3.11/site-packages/locust_plugins/users/__init__.py", line 6, in <module>
    from .mqtt import *
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/lib/python3.11/site-packages/locust_plugins/users/mqtt.py", line 10, in <module>
    import paho.mqtt.client as mqtt
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/lib/python3.11/site-packages/paho/mqtt/client.py", line 72, in <module>
    import dns.resolver
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/lib/python3.11/site-packages/dns/resolver.py", line 30, in <module>
    import dns._ddr
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/lib/python3.11/site-packages/dns/_ddr.py", line 12, in <module>
    import dns.nameserver
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/lib/python3.11/site-packages/dns/nameserver.py", line 5, in <module>
    import dns.asyncquery
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/lib/python3.11/site-packages/dns/asyncquery.py", line 38, in <module>
    from dns.query import (
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/lib/python3.11/site-packages/dns/query.py", line 63, in <module>
    import httpcore
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/lib/python3.11/site-packages/httpcore/__init__.py", line 1, in <module>
    from ._api import request, stream
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/lib/python3.11/site-packages/httpcore/_api.py", line 5, in <module>
    from ._sync.connection_pool import ConnectionPool
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/lib/python3.11/site-packages/httpcore/_sync/__init__.py", line 1, in <module>
    from .connection import HTTPConnection
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 12, in <module>
    from .._synchronization import Lock
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/lib/python3.11/site-packages/httpcore/_synchronization.py", line 13, in <module>
    import trio
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/lib/python3.11/site-packages/trio/__init__.py", line 19, in <module>
    from ._core import TASK_STATUS_IGNORED as TASK_STATUS_IGNORED  # isort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/lib/python3.11/site-packages/trio/_core/__init__.py", line 21, in <module>
    from ._local import RunVar
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/lib/python3.11/site-packages/trio/_core/_local.py", line 5, in <module>
    from . import _run
  File "/Users/username/Library/Caches/pypoetry/virtualenvs/test-service-hXT2vlzW-py3.11/lib/python3.11/site-packages/trio/_core/_run.py", line 2548, in <module>
    raise NotImplementedError("unsupported platform")
NotImplementedError: unsupported platform
```

**Comment by cyberw** [comment]
Try now, using 4.0.0.

**Comment by fannigurt** [comment]
That's cool! 👍🏻
Thank you so much for the update!

чт, 24 серп. 2023 р. о 11:11 Lars Holmberg ***@***.***> пише:
