### ISSUE TITLE
Application Insights - TypeError: 'bool' object is not callable

### ISSUE THREAD

**Issue by dgcode** [SvenskaSpel/locust-plugins#46]
Hey, running locust & locust-plugins using Python 3.9.5 with the following:
* locust==1.5.1
* locust-plugins==1.2.0
* numpy==1.20.2
* pip-tools==6.1.0
* toml==0.10.2

I noticed there's an issue when attempting to use the ApplicationInsights logger:
> [2021-05-05 14:14:16,483] REDACTED/INFO/root: Successfully downloaded Global CA pem file
[2021-05-05 14:14:16,485] REDACTED/INFO/root: Verified using GlobalCAs.pem
[2021-05-05 14:14:16,488] REDACTED/ERROR/root: Uncaught exception in event handler: 
Traceback (most recent call last):
  File "c:\data\sources\performance-testing\venv\lib\site-packages\locust\event.py", line 40, in fire
    handler(**kwargs)
  File "C:\Data\Sources\performance-testing\locust_tests\locust_extension.py", line 40, in app_insights
    ApplicationInsights(env=environment, instrumentation_key="REDACTED")
  File "c:\data\sources\performance-testing\venv\lib\site-packages\locust_plugins\appinsights_listener.py", line 19, in __init__
    self.logger.propagate(propagate_logs)
TypeError: 'bool' object is not callable
> 
> [2021-05-05 14:14:16,488] REDACTED/INFO/locust.main: Run time limit set to 30 seconds
[2021-05-05 14:14:16,488] REDACTED/INFO/locust.main: Starting Locust 1.5.1
[2021-05-05 14:14:16,489] REDACTED/INFO/locust.runners: Spawning 1 users at the rate 1 users/s (0 users already running)...
[2021-05-05 14:14:16,489] REDACTED/INFO/locust.runners: All users spawned: ApiUser: 1 (1 total running)
[2021-05-05 14:14:46,496] REDACTED/INFO/locust.main: Time limit reached. Stopping Locust.
[2021-05-05 14:14:46,497] REDACTED/INFO/locust.runners: Stopping 1 users
[2021-05-05 14:14:46,500] REDACTED/INFO/locust.runners: 1 Users have been stopped, 0 still running
[2021-05-05 14:14:46,526] REDACTED/INFO/locust.main: Running teardowns...
[2021-05-05 14:14:46,526] REDACTED/INFO/locust.main: Shutting down (exit code 2), bye.
[2021-05-05 14:14:46,526] REDACTED/INFO/locust.main: Cleaning up runner...

So nothing gets logged to application insights.

Seems that [line 19 in appinsights_listener.py](https://github.com/SvenskaSpel/locust-plugins/blob/master/locust_plugins/appinsights_listener.py#L19) is attempting to set propagation via the following:
`self.logger.propagate(propagate_logs)`

I understand that I am running on an unsupported version of Python, however according to the [logging docs](https://docs.python.org/3.9/library/logging.html#logging.Logger.propagate) (for all 3.X versions at least), it seems that propagate has always been an attribute not a function, hence the error.

If I change to this:
`self.logger.propagate = propagate_logs`
It fixes the issue:

> [2021-05-05 14:10:26,897] REDACTED/INFO/root: Successfully downloaded Global CA pem file
[2021-05-05 14:10:26,899] REDACTED/INFO/root: Verified using GlobalCAs.pem
[2021-05-05 14:10:26,902] REDACTED/WARNING/root: request_success event deprecated. Use the request event.
[2021-05-05 14:10:26,902] REDACTED/WARNING/root: request_failure event deprecated. Use the request event.
[2021-05-05 14:10:26,902] REDACTED/INFO/root: Added Application Insights listener
[2021-05-05 14:10:26,902] REDACTED/INFO/locust.main: Run time limit set to 30 seconds
[2021-05-05 14:10:26,902] REDACTED/INFO/locust.main: Starting Locust 1.5.1
[2021-05-05 14:10:26,903] REDACTED/INFO/locust.runners: Spawning 1 users at the rate 1 users/s (0 users already running)...
[2021-05-05 14:10:26,903] REDACTED/INFO/locust.runners: All users spawned: ApiUser: 1 (1 total running)
[2021-05-05 14:10:27,825] REDACTED/INFO/locust_plugins.appinsights_listener: Success: GET /api-call Response time: 920.9999999984575 Number of Threads: 1.
[2021-05-05 14:10:29,372] REDACTED/INFO/locust_plugins.appinsights_listener: Success: GET /api-call Response time: 250.0 Number of Threads: 1.
[2021-05-05 14:10:32,275] REDACTED/INFO/locust_plugins.appinsights_listener: Success: GET /api-call Response time: 250.0 Number of Threads: 1.
[2021-05-05 14:10:35,099] REDACTED/INFO/locust_plugins.appinsights_listener: Success: GET /api-call Response time: 281.00000000267755 Number of Threads: 1.
[2021-05-05 14:10:37,848] REDACTED/INFO/locust_plugins.appinsights_listener: Success: GET /api-call Response time: 234.00000000037835 Number of Threads: 1.
[2021-05-05 14:10:40,227] REDACTED/INFO/locust_plugins.appinsights_listener: Success: GET /api-call Response time: 250.0 Number of Threads: 1.
[2021-05-05 14:10:42,074] REDACTED/INFO/locust_plugins.appinsights_listener: Success: GET /api-call Response time: 295.9999999984575 Number of Threads: 1.
[2021-05-05 14:10:44,490] REDACTED/INFO/locust_plugins.appinsights_listener: Success: GET /api-call Response time: 235.00000000058208 Number of Threads: 1.
[2021-05-05 14:10:46,066] REDACTED/INFO/locust_plugins.appinsights_listener: Success: GET /api-call Response time: 235.00000000058208 Number of Threads: 1.
[2021-05-05 14:10:48,365] REDACTED/INFO/locust_plugins.appinsights_listener: Success: GET /api-call Response time: 282.0000000028813 Number of Threads: 1.
[2021-05-05 14:10:50,188] REDACTED/INFO/locust_plugins.appinsights_listener: Success: GET /api-call Response time: 250.0 Number of Threads: 1.
[2021-05-05 14:10:52,505] REDACTED/INFO/locust_plugins.appinsights_listener: Success: GET /api-call Response time: 234.00000000037835 Number of Threads: 1.
[2021-05-05 14:10:54,840] REDACTED/INFO/locust_plugins.appinsights_listener: Success: GET /api-call Response time: 297.0000000022992 Number of Threads: 1.
[2021-05-05 14:10:56,903] REDACTED/INFO/locust.main: Time limit reached. Stopping Locust.
[2021-05-05 14:10:56,904] REDACTED/INFO/locust.runners: Stopping 1 users
[2021-05-05 14:10:56,907] REDACTED/INFO/locust.runners: 1 Users have been stopped, 0 still running
[2021-05-05 14:10:56,950] REDACTED/INFO/locust.main: Running teardowns...
[2021-05-05 14:10:56,951] REDACTED/INFO/locust.main: Shutting down (exit code 0), bye.
[2021-05-05 14:10:56,951] REDACTED/INFO/locust.main: Cleaning up runner...

![image](https://user-images.githubusercontent.com/12691691/117097819-14381080-adb0-11eb-8b73-b0f4d55fd4bd.png)

I am performing some custom logging (lines 1 & 2 in each log) but I don't think they would cause this issue.

**Comment by cyberw** [comment]
@martinpeck Do you have an opinion on this? I dont use it myself, but the change sounds reasonable and I can approve a PR.

**Comment by martinpeck** [comment]
Apologies...yes, this is my fault. Want me to issue a PR to fix?
