### ISSUE TITLE
Issue with  Timescale setup due to git remote show origin

### ISSUE THREAD

**Issue by nck974** [SvenskaSpel/locust-plugins#52]
Hello I'm getting this issue with the Timescale plugin:

```
2021-06-01 13:39:42,184] USER/ERROR/root: Uncaught exception in event handler:
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\locust\event.py", line 40, in fire
    handler(**kwargs)
  File "C:\Users\HMG28\Desktop\performance\locust_files\locustfile.py", line 123, in on_locust_init
    listeners.Timescale(env=environment, testplan="timescale_listener_ex")
  File "c:\python39\lib\site-packages\locust_plugins\listeners.py", line 64, in __init__
    subprocess.check_output(
  File "c:\python39\lib\site-packages\gevent\subprocess.py", line 404, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command 'git remote show origin -n 2>/dev/null | grep h.URL | sed 's/.*://;s/.git$//'' returned non-zero exit status 255.
```

My code:
```python
@events.init.add_listener
def on_locust_init(environment, **_kwargs):
    os.environ["PGHOST"] = "192.168.XXX.XXX"
    os.environ["PGPORT"] = "5432"
    os.environ["PGUSER"] = "test"
    os.environ["PGPASSWORD"] = "test"
    os.environ["PGDATABASE"] = "test_database"
    os.environ["LOCUST_GRAFANA_URL"] = "http://192.168.XXX.XXX:3000/d/YYYYYYY/locust?orgId=1"
    print("On init")
    listeners.Timescale(env=environment, testplan="timescale_listener_ex")
```

I am using the last version installed through `pip` and the locust version is `1.5.3`

If I comment this lines it seems to work:
````python
        # self._gitrepo = (
        #     subprocess.check_output(
        #         "git remote show origin -n 2>/dev/null | grep h.URL | sed 's/.*://;s/.git$//'",
        #         shell=True,
        #         stderr=None,
        #         universal_newlines=True,
        #     )
        #     or None  # default to None instead of empty string
        # )      
        self._gitrepo = None
```

**Comment by cyberw** [comment]
can you try now using latest master?
