### ISSUE TITLE
Getting module 'select' has no attribute 'epoll' 

### ISSUE THREAD

**Issue by habin-163** [SvenskaSpel/locust-plugins#74]
Platform: Linux 16
python3.9
locust==2.8.2
locust-plugins==2.5.1

Log:
File "/opt/jenkins/virtual_env/bugsy_3_9/lib/python3.9/site-packages/locust_plugins/users/playwright.py", line 2, in <module>
    from playwright.async_api import async_playwright
  File "/opt/jenkins/virtual_env/bugsy_3_9/lib/python3.9/site-packages/playwright/async_api/__init__.py", line 23, in <module>
    import playwright.async_api._generated
  File "/opt/jenkins/virtual_env/bugsy_3_9/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "/opt/jenkins/virtual_env/bugsy_3_9/lib/python3.9/site-packages/playwright/_impl/_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "/opt/jenkins/virtual_env/bugsy_3_9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 22, in <module>
    from pyee import AsyncIOEventEmitter
  File "/opt/jenkins/virtual_env/bugsy_3_9/lib/python3.9/site-packages/pyee/__init__.py", line 120, in <module>
    from pyee.trio import TrioEventEmitter as _TrioEventEmitter  # noqa
  File "/opt/jenkins/virtual_env/bugsy_3_9/lib/python3.9/site-packages/pyee/trio.py", line 7, in <module>
    import trio
  File "/opt/jenkins/virtual_env/bugsy_3_9/lib/python3.9/site-packages/trio/__init__.py", line 18, in <module>
    from ._core import (
  File "/opt/jenkins/virtual_env/bugsy_3_9/lib/python3.9/site-packages/trio/_core/__init__.py", line 29, in <module>
    from ._run import (
  File "/opt/jenkins/virtual_env/bugsy_3_9/lib/python3.9/site-packages/trio/_core/_run.py", line 2384, in <module>
    from ._io_epoll import EpollIOManager as TheIOManager
  File "/opt/jenkins/virtual_env/bugsy_3_9/lib/python3.9/site-packages/trio/_core/_io_epoll.py", line 188, in <module>
    class EpollIOManager:
  File "/opt/jenkins/virtual_env/bugsy_3_9/lib/python3.9/site-packages/trio/_core/_io_epoll.py", line 189, in EpollIOManager
    _epoll = attr.ib(factory=select.epoll)
AttributeError: module 'select' has no attribute 'epoll'

**Comment by cyberw** [comment]
Pardon my lack of knowledge of linux distro's but what is Linux 16?

Apparently select.epoll was implemented in Linux 2.5.44

**Comment by cyberw** [comment]
Can you try setting the env var LOCUST_PLAYWRIGHT=1 before running? It might help, and if it does I know how to fix it...

**Comment by habin-prasad** [comment]
> LOCUST_PLAYWRIGHT=1

Earlier issue fixed, but now getting Import errors with PlaywrightScriptUser,pw, event
Log:
from locust_plugins.users.playwright import PlaywrightScriptUser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'PlaywrightScriptUser' from 'locust_plugins.users.playwright'

from locust_plugins.users.playwright import pw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'pw' from 'locust_plugins.users.playwright' 

from locust_plugins.users.playwright import event
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'event' from 'locust_plugins.users.playwright'

**Comment by cyberw** [comment]
Update to latest.

**Comment by habin-prasad** [comment]
locust==2.8.2
locust-plugins==2.5.4
Getting following error now: 

site-packages/locust_plugins/users/playwright.py", line 324, in __init__
self.pwrun = mod.run  # cant name it "run", because that collides with User.run
AttributeError: module 'mod' has no attribute 'run'

**Comment by cyberw** [comment]
Is your playwright recording script really an async python recording?

**Comment by habin-prasad** [comment]
No it is not async one. I might have missed that requirement.  Let me check once with async. Does it have to be a recording ?
